version: "3"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: sent_server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sent
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    expose:
      - 3306
    restart: unless-stopped
